### ISSUE TITLE
How do you find the largest and smallest number in an unsorted integer array? 

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#13]
How do you find the largest and smallest number in an unsorted integer array?

**Comment by Shivashish-rwt** [comment]
I can do that. Please assign this to me.

**Comment by mohitmishra786** [comment]
@Shivashish-rwt  done

**Comment by Shivashish-rwt** [comment]
I have created the pull request. Please review it.

**Comment by Shivashish-rwt** [comment]
@mohitmishra786
