### ISSUE TITLE
How are duplicates removed from a given array in Java?

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#16]
How are duplicates removed from a given array in Java?

**Comment by iam-vipin** [comment]
i can do this assign it to me

**Comment by mohitmishra786** [comment]
@itsvipindev Done, Please star this repo, it really motivates

**Comment by iam-vipin** [comment]
stared the repo i will submit my PR in a while

**Comment by iam-vipin** [comment]
please check PR #110
