### ISSUE TITLE
I have implemented various ML Algorithms that I coded w/o the use of scikit library

### ISSUE THREAD

**Issue by Anmol-Prasad** [mohitmishra786/hacktoberfest-2022#2]
HI Mohit! I have implemented many ML Algorithms that I have implemented from scratch purely in python w/o the use of any library like Scikit-learn. I would love to contribute

**Comment by mohitmishra786** [comment]
Sure , add a PR related to this issue and then I will accept it

**Comment by mohitmishra786** [comment]
@Anmol-Prasad  i have assigned you

**Comment by Anmol-Prasad** [comment]
Thanks a lot and just a request can you please add Hacktoberfest-accepted label to the repository or else Hacktoberfest team won't consider my PR legit

**Comment by Anmol-Prasad** [comment]
I have raised a PR Mohit

**Comment by mohitmishra786** [comment]
Ok
