### ISSUE TITLE
How do you find the length of a singly linked list?

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#29]
How do you find the length of a singly linked list?

**Comment by Pratt2762** [comment]
Can I be assigned this problem? I'd like to work on it.

**Comment by mohitmishra786** [comment]
@Pratt2762 Sure Done, Please star this Repo also, it really motivates

**Comment by Pratt2762** [comment]
Sure, can you let me know in which folder I have to add the code file to?

**Comment by mohitmishra786** [comment]
@Pratt2762 in comptetive coding
