### ISSUE TITLE
Competitive Contests Coding

### ISSUE THREAD

**Issue by PravarAnu** [mohitmishra786/hacktoberfest-2022#3]
Hey @mohitmishra786 I have code of the competitive  contest organised by 

- codechef 
- codeforces
- google kickstart, etc. 

So can you assign this issue to me under the HACKTOBER FEST 2022.

**Comment by mohitmishra786** [comment]
sure, do it

**Comment by PravarAnu** [comment]
I raised a PR regarding this issue. Take a look

**Comment by mohitmishra786** [comment]
Thanks, @PravarAnu  Have a good day
