### ISSUE TITLE
How do you check if a string contains only digits?

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#37]
How do you check if a string contains only digits?

**Comment by iam-vipin** [comment]
i think i can do this with java where i should place this code

**Comment by mohitmishra786** [comment]
@itsvipindev You can place it in Competitive Coding Folder, Done, Please star this repo, it really motivates

**Comment by iam-vipin** [comment]
hey @mohitmishra786 my PR #113 is already merged pleas close this issue with hacktoberfest-accepted label thank you.

**Comment by mohitmishra786** [comment]
@itsvipindev sure
