### ISSUE TITLE
How do you count the occurrence of a given character in a string?

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#40]
How do you count the occurrence of a given character in a string?

**Comment by Ritam135** [comment]
Can you please assign me this?? I would like to contribute to it. And can I use any language??

**Comment by mohitmishra786** [comment]
@Ritam135  Sure, Please start this repo, it really motivates

**Comment by Ritam135** [comment]
you haven't created any issue in your repo. After clicking on fork I cant find this issue

**Comment by mohitmishra786** [comment]
@Ritam135 check it again, as  i do have created it

**Comment by Ritam135** [comment]
Can you please mention me in which folder can I find it ??

**Comment by mohitmishra786** [comment]
@Ritam135 You can create file in competitive coding folder, or if that is not working for you then create it in root directory, I will still accept the PR

**Comment by Ritam135** [comment]
Thanks

**Comment by mohitmishra786** [comment]
@Ritam135 Please star this Repo also, it really motivates

**Comment by Ritam135** [comment]
I have created a pull request on this please check it
