### ISSUE TITLE
How do you reverse words in a given sentence without using any library method?

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#42]
How do you reverse words in a given sentence without using any library method?

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey man, I would like to contribute to this issue, Can you please assign it to me ? Thank you !

**Comment by mohitmishra786** [comment]
@ABHIGYAN-MOHANTA Sure, Please start this repo, it really give boost

**Comment by ABHIGYAN-MOHANTA** [comment]
Thanks.
