### ISSUE TITLE
Do you want to develop awesome games with Python? 

### ISSUE THREAD

**Issue by anand-3399** [mohitmishra786/hacktoberfest-2022#48]
Python has many Graphical User Interface Libraries but for game development Pygame and Kivy Modules are most widely used. Hence I want to contribute in game development with python.

**Comment by mohitmishra786** [comment]
@anand-3399 Sounds great Anand, Please star this Repo also, it really motivates

**Comment by anandjaiswar02** [comment]
I have added the Galaxy Game with python and kivy module
This was the game which was developed in Python and its Kivy module.

1. install [KIVY Module](https://kivy.org/doc/stable-1.10.1/installation/installation-windows.html#:~:text=Install-,kivy,-%3A)
2. Run the main.py file
3. And you are ready to adventure.
