### ISSUE TITLE
How is a binary search tree implemented? 

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#52]
How is a binary search tree implemented?

**Comment by abhaymishra0003** [comment]
A new key in binary search tree is always inserted at a leaf node

**Comment by mohitmishra786** [comment]
@abhaymishra0003 Sure do it and start a pr for it

**Comment by mohitmishra786** [comment]
@abhaymishra0003 Please Star this repo, it really motivates
