### ISSUE TITLE
How do you count the number of leaf nodes in a given binary tree?

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#61]
How do you count the number of leaf nodes in a given binary tree?

**Comment by Anshumansengar** [comment]
Hey, I would Like To help in this. Pls Assign me.

**Comment by mohitmishra786** [comment]
@Anshumansengar Sure, Please star this Repo also, it really motivates

**Comment by Anshumansengar** [comment]
https://github.com/mohitmishra786/hacktoberfest-2022/pull/76
A node is a leaf node if both left and right child nodes of it are NULL. 
Here is an algorithm to get the leaf node count.
getLeafCount(node)
1) If node is NULL then return 0.
2) Else If left and right child nodes are NULL return 1.
3) Else recursively calculate leaf count of the tree using below formula.
    Leaf count of a tree = Leaf count of left subtree + 
                                 Leaf count of right subtree
