### ISSUE TITLE
How is an iterative quicksort algorithm implemented?

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#67]
How is an iterative quicksort algorithm implemented?

**Comment by iamakthecoder** [comment]
I would like to contribute to this. Please assign it to me.

**Comment by iamakthecoder** [comment]
Which programming language is expected to be used? Is C++ fine?

**Comment by mohitmishra786** [comment]
@iamakthecoder yes

**Comment by mohitmishra786** [comment]
@iamakthecoder please star this repo, it really motivates
