### ISSUE TITLE
Find the minimum (or maximum) element of an array

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#80]
Find the minimum (or maximum) element of an array

**Comment by WaniAthar** [comment]
@mohitmishra786  can i help you with this?

**Comment by mohitmishra786** [comment]
@WaniAthar Sure, Please star this Repo also, it really motivates

**Comment by WaniAthar** [comment]
sure!
which programming language you want this to be coded?

**Comment by mohitmishra786** [comment]
@WaniAthar any

**Comment by WaniAthar** [comment]
ok

**Comment by WaniAthar** [comment]
@mohitmishra786 i have created a pull request please check

**Comment by 55ritesh** [comment]
i want to contribute on this assign it to me.

**Comment by mohitmishra786** [comment]
@WaniAthar done

**Comment by mohitmishra786** [comment]
@55ritesh you can also contribute just simply make a PR

**Comment by abhaymishra0003** [comment]
want to work on it

**Comment by nimeshika06** [comment]
@mohitmishra786 please assign this issue to me under hackoberfest2022 tag.

**Comment by ademesojosiah** [comment]
can i help you with this
