### ISSUE TITLE
How to check whether the given number is prime?

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#9]
Write a program to check whether a given number is prime or not?

**Comment by giftade** [comment]
I'd like to solve this

**Comment by mohitmishra786** [comment]
@giftade Sure, Please start this repo, it really motivates

**Comment by giftade** [comment]
where can I add the code to?

**Comment by mohitmishra786** [comment]
@giftade in the competitive coding folder
