### ISSUE TITLE
What steps would you take to identify all pairs of an integer array if the sum is equal to a given number?

### ISSUE THREAD

**Issue by mohitmishra786** [mohitmishra786/hacktoberfest-2022#90]
What steps would you take to identify all pairs of an integer array if the sum is equal to a given number?

**Comment by ABHIGYAN-MOHANTA** [comment]
Man the  repo has been excluded from Hacktoberfest.
![Screenshot from 2022-10-02 01-27-08](https://user-images.githubusercontent.com/110360901/193426228-fb3bbdfb-342b-4f95-85fc-10d5365d37f3.png)

**Comment by mohitmishra786** [comment]
@ABHIGYAN-MOHANTA wait, my sister pr is in review, it didn't got excluded, lemme check again.
